version: '3.8'

services:
  db:
    image: postgres:latest
    restart: always
    container_name: psql_latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      TZ: GMT
    ports:
      - "${PORT}:5432"
